from setuptools import find_packages, setup

setup(
    name="ff_website",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "autopep8",
        "bcrypt",
        "certifi",
        "cffi",
        "click",
        "chardet",
        "dnspython",
        "email-validator",
        "Flask",
        "Flask-Bcrypt"
        "Flask-CLI",
        "Flask-Login",
        "Flask-WTF",
        "idna",
        "importlib-metadata",
        "inflect",
        "itsdangerous",
        "Jinja2",
        "MarkupSafe",
        "mccabe",
        "numpy",
        "pandas",
        "Pillow",
        "pip",
        "pycodestyle",
        "python-dateutil"
        "pytz"
        "setuptools",
        "six",
        "toml",
        "typing-extensions",
        "urllib3",
        "Werkzeug",
        "Flask-WTF",
        "WTForms",
        "zipp"
    ],
)
